version: 2.1
orbs:
  node: circleci/node@5.0.2
  win: circleci/windows@4.1.1

jobs:
  build_and_test_ubuntu:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          override-ci-command: npm install
      - run:
          command: npm run test
          name: Run tests
  test_docker_windows:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            docker info
            docker run -u 1001 -t -v `pwd`:/app/test arsadev/omp-logic:latest

workflows:
  test_my_app:
    jobs:
      - build_and_test
        # &:
        # filters:
        #   branches:
        #     only: main # only deploy when on main
